name: 31s
favicon: null
layout_spectrum: 0.46454290370456874
typography_spectrum: 0.6669083072338253
title: '#31s'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0033ff'
    - '#ffffff'
    - '#231f20'
    - '#7b95ff'
    - '#d2dbff'
  brandStrength: 0.3462374717928469
  lightness: 0.8398879782762378
  saturation: 0.02829430135898292
  rhythmicContrast: 0.2960770328063518
purpose: []
